apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic9-jkhp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/mreid1-tenant/devfile-sample-python-basic9/devfile-sample-python-basic9-jkhp@sha256:b11afebcada6aabca47e250f1ddeae629393bbfaa4eed428227f0f1b87699ef9
        name: my-python
        resources: {}
status: {}
