apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic9-jkhp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/mreid1-tenant/devfile-sample-python-basic9/devfile-sample-python-basic9-jkhp@sha256:f326b597519cae4fbabc4194bc1349a1dc3bd40e09b98e81740b8de841c4d096
        name: my-python
        resources: {}
status: {}
